/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.Auth;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ABC
 */
public class DanhGia_HS extends javax.swing.JInternalFrame {

    /**
     * Creates new form DanhGia
     */
    Random rd = new Random();
    int so = rd.nextInt(1000000);
    String ma_dg = "DG" + so;
    public DanhGia_HS() {
        initComponents();
        connet();
        lblDanhGia.setText(ma_dg);
    }
    
    Connection con;

    protected void connet() {

        String uername = "tuanmayman";
        String password = "vutuan040599";
        String hosting = " sql.freeasphost.net\\MSSQL2016";
        String dbname = "databaseName=tuanmayman_Du_An_1";
//        String url = "jdbc:sqlserver://localhost:1433;databaseName=quan_ly_sach";

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://" + hosting + ";" + dbname, uername, password);
//            JOptionPane.showMessageDialog(this, "Kết nối database thành công !");
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ko có driver");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdoC12 = new javax.swing.JRadioButton();
        rdoC11 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdoC21 = new javax.swing.JRadioButton();
        rdoC22 = new javax.swing.JRadioButton();
        rdoC23 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rdoC31 = new javax.swing.JRadioButton();
        rdoC32 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDanhGia = new javax.swing.JTextArea();
        btnSubMit = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblDanhGia = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Đánh GIá");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Đánh Giá Hệ Thống");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Câu 1: Đề thi có sát với chương trình học không ?");

        buttonGroup1.add(rdoC12);
        rdoC12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC12.setText("Chưa sát chương trình");

        buttonGroup1.add(rdoC11);
        rdoC11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC11.setText("Rất sát chương trình");
        rdoC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoC11ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Câu 2: Đối với bạn đề thi ở mức độ nào ?");

        buttonGroup2.add(rdoC21);
        rdoC21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC21.setText("Khó");

        buttonGroup2.add(rdoC22);
        rdoC22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC22.setText("Trung Bình");

        buttonGroup2.add(rdoC23);
        rdoC23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC23.setText("Dễ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Câu 3: Bạn cảm thấy hệ thống của chúng tôi như thế nào ?");

        buttonGroup3.add(rdoC31);
        rdoC31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC31.setText("Rất tốt");

        buttonGroup3.add(rdoC32);
        rdoC32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoC32.setText("Không tốt");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ý kiến khác : ");

        txtDanhGia.setColumns(20);
        txtDanhGia.setRows(5);
        jScrollPane1.setViewportView(txtDanhGia);

        btnSubMit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Save.png"))); // NOI18N
        btnSubMit.setText("Submit");
        btnSubMit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMitActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/exitot.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblDanhGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDanhGia.setText("         ");

        label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label.setText("Mã đánh giá :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoC12)
                            .addComponent(rdoC11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoC22)
                            .addComponent(rdoC21)
                            .addComponent(rdoC23)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoC32)
                            .addComponent(rdoC31)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnSubMit)
                        .addGap(39, 39, 39)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExit, btnSubMit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDanhGia)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoC11)
                .addGap(6, 6, 6)
                .addComponent(rdoC12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoC21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoC22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoC23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoC31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoC32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubMit)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExit, btnSubMit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoC11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoC11ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSubMitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMitActionPerformed
       

        if (checkForm() == true) {
            try {
                String query = "Insert into DanhGia(Ma_DanhGia,Ma_HocSinh,"
                        + "Cau1,Cau2,Cau3,NoiDungDanhGia,NgayDG) values(?,?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);
                
                 if(check()==true){
                      ps.setString(1,lblDanhGia.getText());
                 }
                ps.setString(2, Auth.user.getMaDN());
                if (rdoC11.isSelected() == true) {
                    ps.setString(3, rdoC11.getText());
                } else if (rdoC12.isSelected() == true) {
                    ps.setString(3, rdoC12.getText());
                }
                if (rdoC21.isSelected() == true) {
                    ps.setString(4, rdoC21.getText());
                } else if (rdoC22.isSelected() == true) {
                    ps.setString(4, rdoC22.getText());
                } else {
                    ps.setString(4, rdoC23.getText());
                }
                if (rdoC31.isSelected() == true) {
                    ps.setString(5, rdoC31.getText());
                } else if (rdoC32.isSelected() == true) {
                    ps.setString(5, rdoC32.getText());
                }
                ps.setString(6, txtDanhGia.getText());
                ps.setDate(7, Date.valueOf(LocalDate.now().toString()));
//                ps.setDate(7,Date.valueOf("2020-06-18"));
                ps.execute();
                clear();
                JOptionPane.showMessageDialog(this, "Cảm ơn bạn đã đánh giá !");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSubMitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubMit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblDanhGia;
    private javax.swing.JRadioButton rdoC11;
    private javax.swing.JRadioButton rdoC12;
    private javax.swing.JRadioButton rdoC21;
    private javax.swing.JRadioButton rdoC22;
    private javax.swing.JRadioButton rdoC23;
    private javax.swing.JRadioButton rdoC31;
    private javax.swing.JRadioButton rdoC32;
    private javax.swing.JTextArea txtDanhGia;
    // End of variables declaration//GEN-END:variables

    private boolean checkForm() {
        if (rdoC11.isSelected() == false && rdoC12.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Bạn chưa trả lời câu 1 !");
            return false;
        } else if (rdoC21.isSelected() == false && rdoC22.isSelected() == false && rdoC23.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Bạn chưa trả lời câu 2 !");
            return false;
        } else if (rdoC31.isSelected() == false && rdoC32.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Bạn chưa trả lời câu 3 !");
            return false;
        } else if (txtDanhGia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ý kiến của bạn !");
            txtDanhGia.requestFocus();
            return false;
        }

        return true;
    }
    
    public  boolean check(){
        try {
                    String sql="Select * from danhgia where Ma_DanhGia like N'%"+lblDanhGia.getText().trim()+"%'";
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    if(rs.next()){
//                        JOptionPane.showMessageDialog(this,"Mã đánh giá bị trùng !");
                        so = rd.nextInt(1000000);
                        ma_dg = "DG" + so;
                        lblDanhGia.setText(ma_dg);
                        return false;
                    }else{
                        lblDanhGia.setText(ma_dg);
                        return true;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
     return true;
    
    }
    void clear(){
        so = rd.nextInt(1000000);
         ma_dg = "DG" + so;
        lblDanhGia.setText(ma_dg);
        txtDanhGia.setText("");
        
    }
}
