/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.Auth;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class main_QL extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienQuanLy
     */
    public main_QL() {
        initComponents();
        setLocationRelativeTo(null);
        System.out.println(jDesktopPane.size());
        //check dang nhập
        setDongHo();
        if (Auth.isLogin()) {
            this.HienThi();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập!");
            return;
        }

    }
    String imageName = null;

    public void upHinh(String imageName) {
        ImageIcon icon = new ImageIcon("src\\TienIch\\Icon\\" + imageName);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(125, 200, image.SCALE_SMOOTH));
        lbHinh.setIcon(icon1);
    }

    protected void HienThi() {
        imageName = Auth.user.getHinh();
        this.upHinh(imageName);
        lbTen.setText(Auth.user.getHoTen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTen = new javax.swing.JLabel();
        btnTrangChu = new javax.swing.JButton();
        btnTheLoai = new javax.swing.JButton();
        btnMonHoc = new javax.swing.JButton();
        btnDeThi = new javax.swing.JButton();
        btnCauHoi = new javax.swing.JButton();
        btnGiaoVien = new javax.swing.JButton();
        btnDanhGia = new javax.swing.JButton();
        lbHinh = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniTheLoai = new javax.swing.JMenuItem();
        mniMonHoc = new javax.swing.JMenuItem();
        mniQLdethi = new javax.swing.JMenuItem();
        mniCauHoi = new javax.swing.JMenuItem();
        mniGiaoVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniBangDiem = new javax.swing.JMenuItem();
        mniSoLuongDangKy = new javax.swing.JMenuItem();
        mniDeThi = new javax.swing.JMenuItem();
        mniDiemTBMon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao Diện Quản Lý");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTen.setText("Nguyễn Văn A");

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Home.png"))); // NOI18N
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnTheLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/theloai.png"))); // NOI18N
        btnTheLoai.setText("QL Môn Học");
        btnTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheLoaiActionPerformed(evt);
            }
        });

        btnMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monhoc.png"))); // NOI18N
        btnMonHoc.setText("QL Môn Học Chi Tiết");
        btnMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonHocActionPerformed(evt);
            }
        });

        btnDeThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Notes.png"))); // NOI18N
        btnDeThi.setText("QL Đề Thi");
        btnDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeThiActionPerformed(evt);
            }
        });

        btnCauHoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Task list.png"))); // NOI18N
        btnCauHoi.setText("QL Câu Hỏi");
        btnCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauHoiActionPerformed(evt);
            }
        });

        btnGiaoVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGiaoVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/User.png"))); // NOI18N
        btnGiaoVien.setText("QL Giáo Viên");
        btnGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoVienActionPerformed(evt);
            }
        });

        btnDanhGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDanhGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Favourites.png"))); // NOI18N
        btnDanhGia.setText("Xem Đánh Giá");
        btnDanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhGiaActionPerformed(evt);
            }
        });

        lbHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/loginuser.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDanhGia)
                            .addComponent(btnGiaoVien)
                            .addComponent(btnCauHoi)
                            .addComponent(btnDeThi)
                            .addComponent(btnMonHoc)
                            .addComponent(btnTheLoai)
                            .addComponent(btnTrangChu)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lbTen)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCauHoi, btnDanhGia, btnDeThi, btnGiaoVien, btnMonHoc, btnTheLoai, btnTrangChu});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(lbTen)
                .addGap(41, 41, 41)
                .addComponent(btnTrangChu)
                .addGap(18, 18, 18)
                .addComponent(btnTheLoai)
                .addGap(18, 18, 18)
                .addComponent(btnMonHoc)
                .addGap(18, 18, 18)
                .addComponent(btnDeThi)
                .addGap(18, 18, 18)
                .addComponent(btnCauHoi)
                .addGap(18, 18, 18)
                .addComponent(btnGiaoVien)
                .addGap(18, 18, 18)
                .addComponent(btnDanhGia)
                .addGap(32, 32, 32))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCauHoi, btnDeThi, btnGiaoVien, btnMonHoc, btnTheLoai, btnTrangChu});

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        lblDongHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("                                          ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(758, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );

        jDesktopPane.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("HỆ THỐNG");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Exit.png"))); // NOI18N
        jMenuItem6.setText("Đăng Xuất");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/exitot.png"))); // NOI18N
        jMenuItem7.setText("Thoát");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Favourites.png"))); // NOI18N
        jMenuItem8.setText("Đánh Giá");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/thungrac.png"))); // NOI18N
        jMenuItem9.setText("Thùng Rác");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("QUẢN LÝ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/theloai.png"))); // NOI18N
        mniTheLoai.setText("Môn Học");
        mniTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTheLoaiActionPerformed(evt);
            }
        });
        jMenu2.add(mniTheLoai);

        mniMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monhoc.png"))); // NOI18N
        mniMonHoc.setText("Môn Học Chi Tiết");
        mniMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMonHocActionPerformed(evt);
            }
        });
        jMenu2.add(mniMonHoc);

        mniQLdethi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Notes.png"))); // NOI18N
        mniQLdethi.setText("Đề Thi");
        mniQLdethi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLdethiActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLdethi);

        mniCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Task list.png"))); // NOI18N
        mniCauHoi.setText("Câu Hỏi");
        mniCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCauHoiActionPerformed(evt);
            }
        });
        jMenu2.add(mniCauHoi);

        mniGiaoVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/User.png"))); // NOI18N
        mniGiaoVien.setText("Giáo Viên");
        mniGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGiaoVienActionPerformed(evt);
            }
        });
        jMenu2.add(mniGiaoVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("THỐNG KÊ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Numbered list.png"))); // NOI18N
        mniBangDiem.setText("Bảng Điểm");
        mniBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemActionPerformed(evt);
            }
        });
        jMenu3.add(mniBangDiem);

        mniSoLuongDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/soluonghs.png"))); // NOI18N
        mniSoLuongDangKy.setText("Số Lượng Đăng Ký");
        mniSoLuongDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSoLuongDangKyActionPerformed(evt);
            }
        });
        jMenu3.add(mniSoLuongDangKy);

        mniDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/tk_dethi.png"))); // NOI18N
        mniDeThi.setText("Đề Thi");
        mniDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeThiActionPerformed(evt);
            }
        });
        jMenu3.add(mniDeThi);

        mniDiemTBMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Best.png"))); // NOI18N
        mniDiemTBMon.setText("Điểm TB Môn");
        mniDiemTBMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemTBMonActionPerformed(evt);
            }
        });
        jMenu3.add(mniDiemTBMon);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void close() {
        for (JInternalFrame jif : jDesktopPane.getAllFrames()) {
            jif.dispose();
        }
    }
    private void btnGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoVienActionPerformed
        close();
        QLGiaoVien ql = new QLGiaoVien();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_btnGiaoVienActionPerformed

    private void btnTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheLoaiActionPerformed
        close();
        QLMonHoc ql = new QLMonHoc();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_btnTheLoaiActionPerformed

    private void btnMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonHocActionPerformed
        close();
        QLMonHocChiTiet ql = new QLMonHocChiTiet();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_btnMonHocActionPerformed

    private void btnDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeThiActionPerformed
        close();
        QLDeThi ql = new QLDeThi();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_btnDeThiActionPerformed

    private void btnCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCauHoiActionPerformed
        close();
        QLCauHoi ql = new QLCauHoi();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_btnCauHoiActionPerformed

    private void btnDanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhGiaActionPerformed
        close();
        DanhGia_GV ql = new DanhGia_GV();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_btnDanhGiaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?");
        if (a != JOptionPane.YES_OPTION) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?");
        if (a != JOptionPane.YES_OPTION) {
            return;
        }
        Auth.clear();
        main_Run chao = new main_Run();
        chao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mniBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemActionPerformed
        close();
        TongHop_ThongKe ql = new TongHop_ThongKe();
        TongHop_ThongKe.tabs.setSelectedIndex(0);
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniBangDiemActionPerformed

    private void mniSoLuongDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSoLuongDangKyActionPerformed
        close();
        TongHop_ThongKe ql = new TongHop_ThongKe();
        TongHop_ThongKe.tabs.setSelectedIndex(1);
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniSoLuongDangKyActionPerformed

    private void mniDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeThiActionPerformed
        close();
        TongHop_ThongKe ql = new TongHop_ThongKe();
        TongHop_ThongKe.tabs.setSelectedIndex(2);
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniDeThiActionPerformed

    private void mniDiemTBMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemTBMonActionPerformed
        close();
        TongHop_ThongKe ql = new TongHop_ThongKe();
        TongHop_ThongKe.tabs.setSelectedIndex(3);
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniDiemTBMonActionPerformed

    private void mniTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTheLoaiActionPerformed
        close();
        QLMonHoc ql = new QLMonHoc();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniTheLoaiActionPerformed

    private void mniMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMonHocActionPerformed
        close();
        QLMonHocChiTiet ql = new QLMonHocChiTiet();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniMonHocActionPerformed

    private void mniQLdethiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLdethiActionPerformed
        close();
        QLDeThi ql = new QLDeThi();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniQLdethiActionPerformed

    private void mniCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCauHoiActionPerformed
        close();
        QLCauHoi ql = new QLCauHoi();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniCauHoiActionPerformed

    private void mniGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGiaoVienActionPerformed
        close();
        QLGiaoVien ql = new QLGiaoVien();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_mniGiaoVienActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        close();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        close();
        DanhGia_GV ql = new DanhGia_GV();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        close();
        ThungRac ql = new ThungRac();
        jDesktopPane.add(ql);
        ql.setLocation((jDesktopPane.getWidth() - ql.getWidth()) / 2,
                 (jDesktopPane.getHeight() - ql.getHeight()) / 2);
        ql.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_QL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCauHoi;
    private javax.swing.JButton btnDanhGia;
    private javax.swing.JButton btnDeThi;
    private javax.swing.JButton btnGiaoVien;
    private javax.swing.JButton btnMonHoc;
    private javax.swing.JButton btnTheLoai;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbHinh;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniCauHoi;
    private javax.swing.JMenuItem mniDeThi;
    private javax.swing.JMenuItem mniDiemTBMon;
    private javax.swing.JMenuItem mniGiaoVien;
    private javax.swing.JMenuItem mniMonHoc;
    private javax.swing.JMenuItem mniQLdethi;
    private javax.swing.JMenuItem mniSoLuongDangKy;
    private javax.swing.JMenuItem mniTheLoai;
    // End of variables declaration//GEN-END:variables

    private void setDongHo() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date tg = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                String date = sdf.format(tg);
                lblDongHo.setText(date);
            }
        }).start();
    }
}
