/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.Auth;
import Entity.EntityThi;
import static Form.main_HS.jDesktopPaneHS;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ABC
 */
public class QLThi extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form QLThi
     */
    int size = 100;
    JButton[] btt = new JButton[size];
    ArrayList<EntityThi> listCH = new ArrayList<>();
    String DapAn_Chon = null;
    public static Connection con;
    int viTri = 0;
    String imgCH = null;
    int indexDomau = 0;

    public QLThi() {
        initComponents();
        disableMenu();
        connect();
        layCH();
        createBtt();
        if (btt.length > 0) {
            hienThi(btt[0].getName());
        }
        ThongTinDeThi();
        HamThoiGian();
        setDongHo();
        HienThiAnh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pgbThoiGian = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        chkCau1 = new javax.swing.JCheckBox();
        chkCau2 = new javax.swing.JCheckBox();
        chkCau3 = new javax.swing.JCheckBox();
        chkCau4 = new javax.swing.JCheckBox();
        lblAnhCauHoi = new javax.swing.JLabel();
        lblSoCauHoi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        lblHoTen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMon = new javax.swing.JLabel();
        lblDoKho = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMaDe = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnNop = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        lblAnhHocSinh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTongSoCau = new javax.swing.JLabel();
        lblDemNguocTG = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Thi");
        setToolTipText("");

        pgbThoiGian.setStringPainted(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnFirst)
                .addGap(18, 18, 18)
                .addComponent(btnPrev)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addGap(18, 18, 18)
                .addComponent(btnLast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrev)
                        .addComponent(btnFirst)
                        .addComponent(btnLast)))
                .addContainerGap())
        );

        chkCau1.setText("C1");
        chkCau1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCau1MouseClicked(evt);
            }
        });

        chkCau2.setText("C2");
        chkCau2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCau2MouseClicked(evt);
            }
        });

        chkCau3.setText("C3");
        chkCau3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCau3MouseClicked(evt);
            }
        });

        chkCau4.setText("C4");
        chkCau4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCau4MouseClicked(evt);
            }
        });

        lblAnhCauHoi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSoCauHoi.setText("Câu Hỏi :");

        txtNoiDung.setColumns(20);
        txtNoiDung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSoCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCau2)
                            .addComponent(chkCau3)
                            .addComponent(chkCau4)
                            .addComponent(chkCau1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnhCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblSoCauHoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkCau1)
                        .addGap(18, 18, 18)
                        .addComponent(chkCau2)
                        .addGap(18, 18, 18)
                        .addComponent(chkCau3)
                        .addGap(18, 18, 18)
                        .addComponent(chkCau4)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAnhCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblHoTen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHoTen.setText("Trần Văn A");

        jLabel4.setText("Họ tên HS :");

        jLabel5.setText("Môn thi :");

        lblMon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMon.setText("Toán");

        lblDoKho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDoKho.setText("Dễ");

        jLabel6.setText("Độ khó :");

        jLabel7.setText("Mã đề :");

        lblMaDe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMaDe.setText("001");

        lblThoiGian.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblThoiGian.setText("20");

        jLabel8.setText("Thời gian :");

        btnNop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Accept.png"))); // NOI18N
        btnNop.setText("Hoàn thành");
        btnNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/exitot.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Thời gian làm bài");

        panelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelButton.setLayout(new java.awt.GridLayout(1, 0));

        lblAnhHocSinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Số câu");

        lblTongSoCau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongSoCau.setText("20");

        lblDemNguocTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/Alarm.png"))); // NOI18N

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin.setText("jLabel1");

        lblSec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSec.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(":");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lblDemNguocTG)
                                .addGap(18, 18, 18)
                                .addComponent(lblMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pgbThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblAnhHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDoKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblMaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTongSoCau, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(btnNop)
                .addGap(101, 101, 101)
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExit, btnNop});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDemNguocTG)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(pgbThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMin)
                        .addComponent(lblSec)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblAnhHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblMon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblMaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblThoiGian))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblTongSoCau)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNop)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCau4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCau4MouseClicked
        EntityThi en = listCH.get(viTri);
        if (chkCau4.isSelected()) {
            en.setDapAn_Chon(chkCau4.getText());
            chkCau1.setSelected(false);
            chkCau2.setSelected(false);
            chkCau3.setSelected(false);
            System.out.println(en.getDapAn_Chon());
            System.out.println("DaClick");
            //đổ màu
            btt[indexDomau].setBackground(Color.YELLOW);
        } else {
            en.setDapAn_Chon("chưa chọn");
            btt[indexDomau].setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_chkCau4MouseClicked

    private void chkCau3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCau3MouseClicked
        EntityThi en = listCH.get(viTri);
        if (chkCau3.isSelected()) {
            en.setDapAn_Chon(chkCau3.getText());
            chkCau1.setSelected(false);
            chkCau2.setSelected(false);
            chkCau4.setSelected(false);
            System.out.println(en.getDapAn_Chon());
            System.out.println("DaClick");
            //đổ màu
            btt[indexDomau].setBackground(Color.YELLOW);
        } else {
            en.setDapAn_Chon("chưa chọn");
            btt[indexDomau].setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_chkCau3MouseClicked

    private void chkCau2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCau2MouseClicked
        EntityThi en = listCH.get(viTri);
        if (chkCau2.isSelected()) {
            en.setDapAn_Chon(chkCau2.getText());
            chkCau1.setSelected(false);
            chkCau3.setSelected(false);
            chkCau4.setSelected(false);
            System.out.println(en.getDapAn_Chon());
            System.out.println("DaClick");
            //đổ màu
            btt[indexDomau].setBackground(Color.YELLOW);
        } else {
            en.setDapAn_Chon("chưa chọn");
            btt[indexDomau].setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_chkCau2MouseClicked

    private void chkCau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCau1MouseClicked
        EntityThi en = listCH.get(viTri);
        if (chkCau1.isSelected()) {
            en.setDapAn_Chon(chkCau1.getText());
            chkCau2.setSelected(false);
            chkCau3.setSelected(false);
            chkCau4.setSelected(false);
            System.out.println(en.getDapAn_Chon());
            System.out.println("DaClick");
            //đổ màu
            btt[indexDomau].setBackground(Color.YELLOW);
        } else {
            en.setDapAn_Chon("chưa chọn");
            btt[indexDomau].setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_chkCau1MouseClicked

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        viTri = this.listCH.size() - 1;
        hienThi(viTri + "");
        EntityThi et = listCH.get(viTri);
        UpHinhCH(et.getHinh());
        indexDomau = viTri;
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (viTri < this.listCH.size() - 1) {
            viTri++;
        } else if (viTri == this.listCH.size() - 1) {
            viTri = 0;
        }
        //hiển thị
        hienThi(viTri + "");
        //up hình câu hỏi
        EntityThi et = listCH.get(viTri);
        UpHinhCH(et.getHinh());
        //vi trí đổ màu if selected
        indexDomau = viTri;
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        viTri = 0;
        hienThi(viTri + "");
        EntityThi et = listCH.get(viTri);
        UpHinhCH(et.getHinh());
        indexDomau = viTri;
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if (viTri > 0) {
            viTri--;
        } else if (viTri == 0) {
            viTri = this.listCH.size() - 1;
        }
        hienThi(viTri + "");
        EntityThi et = listCH.get(viTri);
        UpHinhCH(et.getHinh());
        indexDomau = viTri;
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int ck = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát?");
        if (ck != JOptionPane.YES_OPTION) {
            return;
        }
        this.dispose();
        enableMenu();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopActionPerformed
        int ck = JOptionPane.showConfirmDialog(this, "Bạn muốn kết thúc bài thi?");
        if (ck != JOptionPane.YES_OPTION) {
            return;
        }
        KQ();
    }//GEN-LAST:event_btnNopActionPerformed

    protected void connect() {
        String uername = "tuanmayman";
        String password = "vutuan040599";
        String hosting = " sql.freeasphost.net\\MSSQL2016";
        String dbname = "databaseName=tuanmayman_Du_An_1";
//        String url = "jdbc:sqlserver://localhost:1433;databaseName=quan_ly_sach";

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://" + hosting + ";" + dbname, uername, password);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Không tìm thấy Driver tương thích !");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Kết nốt thất bại !");
        }
    }

    protected void layCH() {
        try {
            String maDeThi = ChonDeThi_HS.maDe;
            Statement st = con.createStatement();
            String sql = "select dtct.Ma_CauHoi,ch.NoiDung_CauHoi,DapAn_A,DapAn_B,DapAn_C,DapAn_D,DapAn_Dung,Hinh\n"
                    + "from DETHI dt inner join DETHICHITIET dtct on dt.Ma_DeThi=dtct.Ma_DeThi\n"
                    + "	inner join CAUHOI ch on dtct.Ma_CauHoi=ch.Ma_CauHoi\n"
                    + "where dt.Ma_DeThi like N'" + maDeThi + "'";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String Ma_CauHoi = rs.getString("Ma_CauHoi");
                String NoiDung_CauHoi = rs.getString("NoiDung_CauHoi");
                String DapAn_A = rs.getString("DapAn_A");
                String DapAn_B = rs.getString("DapAn_B");
                String DapAn_C = rs.getString("DapAn_C");
                String DapAn_D = rs.getString("DapAn_D");
                String DapAn_Dung = rs.getString("DapAn_Dung");
                String Hinh = rs.getString("Hinh");
                DapAn_Chon = "chưa chọn";
                listCH.add(new EntityThi(Ma_CauHoi, NoiDung_CauHoi, DapAn_A,
                        DapAn_B, DapAn_C, DapAn_D, DapAn_Dung, Hinh, DapAn_Chon));
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLThi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    protected void createBtt() {
        int r = -1;
        panelButton.setLayout(new GridLayout(3, size));
        for (EntityThi bt : listCH) {
            r++;
            System.out.println(bt.getMa_CauHoi());
            btt[r] = new JButton(r + 1 + "");
            btt[r].setName(r + "");
            btt[r].addActionListener(this);
            btt[r].setSize(40, 25);
            panelButton.add(btt[r]);

        }

    }

    protected void hienThi(String index) {
        int index1 = Integer.parseInt(index);
        EntityThi en = listCH.get(index1);
        lblSoCauHoi.setText("Câu Hỏi " + (index1 + 1) + ":");
        txtNoiDung.setText(en.getNoiDung_CauHoi());
        txtNoiDung.setEnabled(false);
        chkCau1.setText(en.getDapAn_A());
        chkCau2.setText(en.getDapAn_B());
        chkCau3.setText(en.getDapAn_C());
        chkCau4.setText(en.getDapAn_D());
//        lblAnhCauHoi.setText(en.getHinh());
        imgCH = en.getHinh();

//        System.out.println(index1);
        clear();
        if (chkCau1.getText().equals(en.getDapAn_Chon())) {
            chkCau1.setSelected(true);
        } else if (chkCau2.getText().equals(en.getDapAn_Chon())) {
            chkCau2.setSelected(true);
        } else if (chkCau3.getText().equals(en.getDapAn_Chon())) {
            chkCau3.setSelected(true);
        } else if (chkCau4.getText().equals(en.getDapAn_Chon())) {
            chkCau4.setSelected(true);
        }
    }

    protected void clear() {
        chkCau1.setSelected(false);
        chkCau2.setSelected(false);
        chkCau3.setSelected(false);
        chkCau4.setSelected(false);
    }

    protected void disableMenu() {
        main_HS.jMenu1.disable();
        main_HS.jMenu2.disable();
        main_HS.jMenu3.disable();
        main_HS.jMenu4.disable();
        main_HS.jMenu5.disable();
    }

    protected void enableMenu() {
        main_HS.jMenu1.enable();
        main_HS.jMenu2.enable();
        main_HS.jMenu3.enable();
        main_HS.jMenu4.enable();
        main_HS.jMenu5.enable();
    }

    int time = 1;
    int soCauDung = 0;
    int socau = 0;

    protected void KQ() {
        for (EntityThi en : listCH) {
            socau++;
            String daChon = en.getDapAn_Chon();
            String daDung = en.getDapAn_Dung();
            System.out.println(daChon + "///" + daDung);
            if (daChon.equals(daDung)) {
                soCauDung++;
                System.out.println("True\n");
            } else {
                System.out.println("False\n");
            }
        }
        System.out.println("Số câu đúng:" + soCauDung + "/" + socau);
        if (time == 0) {
            JOptionPane.showMessageDialog(rootPane, "Hết thời gian làm bài !");
        }
        time = 1;
//        JOptionPane.showMessageDialog(this, "Số câu đúng:" + soCauDung + "/" + socau);

        //show form socaudung
        KetQua.socaudung = soCauDung;
        KetQua.socau = socau;
        KetQua.mon = ChonDeThi_HS.theloai;
        KetQua.dokho = ChonDeThi_HS.doKho;
        KetQua kq = new KetQua();
        jDesktopPaneHS.add(kq);
        kq.setLocation((jDesktopPaneHS.getWidth() - kq.getWidth()) / 2, (jDesktopPaneHS.getHeight() - kq.getHeight()) / 2);
        kq.setVisible(true);
        //
        //mo khoa menu
        enableMenu();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNop;
    private javax.swing.JButton btnPrev;
    private javax.swing.JCheckBox chkCau1;
    private javax.swing.JCheckBox chkCau2;
    private javax.swing.JCheckBox chkCau3;
    private javax.swing.JCheckBox chkCau4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhCauHoi;
    private javax.swing.JLabel lblAnhHocSinh;
    private javax.swing.JLabel lblDemNguocTG;
    private javax.swing.JLabel lblDoKho;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaDe;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMon;
    private javax.swing.JLabel lblSec;
    private javax.swing.JLabel lblSoCauHoi;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblTongSoCau;
    private javax.swing.JPanel panelButton;
    private javax.swing.JProgressBar pgbThoiGian;
    private javax.swing.JTextArea txtNoiDung;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        for (int r = 0; r < size; r++) {
            if (e.getSource() == btt[r]) {
                indexDomau = r;
                viTri = Integer.parseInt(btt[r].getName());
                //lấy hình câu hỏi
                EntityThi et = listCH.get(r);
                UpHinhCH(et.getHinh());
//                System.out.println(btt[r].getName());
                //show câu hỏi
                hienThi(btt[r].getName());
            }
        }
    }

    private void ThongTinDeThi() {
        lblMon.setText(ChonDeThi_HS.theloai);
        lblDoKho.setText(ChonDeThi_HS.doKho);
        lblThoiGian.setText(ChonDeThi_HS.thoiGian + "");
        lblTongSoCau.setText(ChonDeThi_HS.soCau + "");
        lblMaDe.setText(ChonDeThi_HS.maDe);
    }

    private void HamThoiGian() {
        //1 phut chay het 100% delay trong 600s
        int thoiGian = ChonDeThi_HS.thoiGian * 600;
        new Timer(thoiGian, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                int value = pgbThoiGian.getValue();
                if (value < pgbThoiGian.getMaximum()) {
                    pgbThoiGian.setValue(value + 1);
                } else {
                    return;
                }
            }
        }).start();
    }

    int min, sec;
    Timer timer;

    private void setDongHo() {

        min = ChonDeThi_HS.thoiGian;
//        min=1;
        sec = 0;
        //sec la giay
        //min la phut
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //giay bang 0 thi chay lai min
                lblMin.setForeground(Color.BLACK);
                lblSec.setForeground(Color.BLACK);
                if (sec == 0) {
                    sec = 60;
                    min--;
                }
                if (min < 0) {
                    time = 0;
                    KQ();
                    min = 0;
                    sec = 0;
                    timer.stop();
                    return;
                    //dung khi phut<0
                } else {
                    sec--;
                    if (min < 10) {
                        lblMin.setForeground(Color.RED);
                        lblSec.setForeground(Color.RED);
                    }
                    lblMin.setText(min + " m");
                    lblSec.setText(sec + " s");
                }
            }
        });
        timer.start();
    }

    protected void HienThiAnh() {
        String imgHocSinh = Auth.user.getHinh();
        this.UpHinhHS(imgHocSinh);
        this.UpHinhCH(imgCH);
        lblHoTen.setText(Auth.user.getHoTen());
    }

    protected void UpHinhHS(String imageHS) {
        ImageIcon icon = new ImageIcon("src\\TienIch\\Icon\\" + imageHS);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(132, 162, image.SCALE_SMOOTH));
        lblAnhHocSinh.setIcon(icon1);
    }

    protected void UpHinhCH(String imageCH) {
        ImageIcon icon = new ImageIcon("src\\TienIch\\Icon\\" + imageCH);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(132, 162, image.SCALE_SMOOTH));
        lblAnhCauHoi.setIcon(icon1);
    }
}
