/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JInternalFrame;
import static Form.main_HS.jDesktopPaneHS;

/**
 *
 * @author Hello Kiên
 */
public class TrangChu_HS extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrangChu_HS
     */
    public TrangChu_HS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLy = new javax.swing.JButton();
        btnHoa = new javax.swing.JButton();
        btnSinh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnToan = new javax.swing.JButton();
        btnVan = new javax.swing.JButton();
        btnAnh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnSu = new javax.swing.JButton();
        btnDia = new javax.swing.JButton();
        btnGDCD = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Hệ thống ôn thi THPT_HS");
        setPreferredSize(new java.awt.Dimension(790, 650));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(813, 680));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HỆ THỐNG ÔN THI THPT");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Môn khoa học tự nhiên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnLy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monvatly.png"))); // NOI18N
        btnLy.setText("Lý");
        btnLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLyActionPerformed(evt);
            }
        });

        btnHoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monhoahoc.png"))); // NOI18N
        btnHoa.setText("Hóa");
        btnHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaActionPerformed(evt);
            }
        });

        btnSinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monsinhhoc.png"))); // NOI18N
        btnSinh.setText("Sinh");
        btnSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnLy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(btnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHoa, btnLy, btnSinh});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHoa, btnLy, btnSinh});

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Môn cơ bản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/toan.png"))); // NOI18N
        btnToan.setText("Toán");
        btnToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToanActionPerformed(evt);
            }
        });

        btnVan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monvan.png"))); // NOI18N
        btnVan.setText("Văn");
        btnVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVanActionPerformed(evt);
            }
        });

        btnAnh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monta.png"))); // NOI18N
        btnAnh.setText("Anh");
        btnAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnToan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnVan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnh, btnToan, btnVan});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnh, btnToan, btnVan});

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Môn khoa học xã hội", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnSu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/monlichsu.png"))); // NOI18N
        btnSu.setText("Sử");
        btnSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuActionPerformed(evt);
            }
        });

        btnDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/mondialy.png"))); // NOI18N
        btnDia.setText("Địa");
        btnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaActionPerformed(evt);
            }
        });

        btnGDCD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGDCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TienIch/Icon/giaoduccongdan.png"))); // NOI18N
        btnGDCD.setText("GDCD");
        btnGDCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGDCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnSu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDia, btnGDCD, btnSu});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSu))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDia, btnGDCD, btnSu});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel4, jPanel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel4, jPanel5});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToanActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnToan.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnToanActionPerformed

    private void btnVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVanActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnVan.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnVanActionPerformed

    private void btnAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnAnh.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnAnhActionPerformed

    private void btnLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLyActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnLy.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnLyActionPerformed

    private void btnHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnHoa.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnHoaActionPerformed

    private void btnSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnSinh.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnSinhActionPerformed

    private void btnSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnSu.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnSuActionPerformed

    private void btnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnDia.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnDiaActionPerformed

    private void btnGDCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGDCDActionPerformed
        for (JInternalFrame jif : jDesktopPaneHS.getAllFrames()) {
            jif.dispose();
        }
        ChonDeThi_HS.theloai = btnGDCD.getText();
        ChonDeThi_HS tc = new ChonDeThi_HS();
        jDesktopPaneHS.add(tc);
        tc.setLocation((jDesktopPaneHS.getWidth() - tc.getWidth()) / 2, (jDesktopPaneHS.getHeight() - tc.getHeight()) / 2);
        tc.setVisible(true);
    }//GEN-LAST:event_btnGDCDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnh;
    private javax.swing.JButton btnDia;
    private javax.swing.JButton btnGDCD;
    private javax.swing.JButton btnHoa;
    private javax.swing.JButton btnLy;
    private javax.swing.JButton btnSinh;
    private javax.swing.JButton btnSu;
    private javax.swing.JButton btnToan;
    private javax.swing.JButton btnVan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
